"""
Django settings for Systeme_Alerte project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
import environ
from decouple import config
PORT = os.environ.get("PORT", "10000")
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
########################################

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"


# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Chemin absolu du fichier modèle
MODEL_PATH = os.path.join(BASE_DIR, "Fruit", "models", "shape_classifier.h5")

##########################################

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# env = environ.Env()
# environ.Env.read.env()

env = environ.Env()  # Créer une instance de l'environnement
env.read_env()  # Lire les variables depuis le fichier .env


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t%w#xp&_q6&_gp#gpt_(xu)olwr_haq@h(#b0kx)&c0s&+n=%8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders', #permet la communication entre backend et react
    'account',
    'Fruit',
    
    # 'allauth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Systeme_Alerte.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
         'account.auth.backends.JWTAuthentication',  ),
}
WSGI_APPLICATION = 'Systeme_Alerte.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "https://projet-backend-4027.vercel.app",
]

# CORS_ALLOWED_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    "https://projet-backend-4027.vercel.app",  # Autorise les requêtes sécurisées
]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  # URL de React
# ]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        env("DATABASE_URL")  # Charge l'URL de Render depuis les variables d'environnement
    )
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'account.User' 


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587 
EMAIL_HOST_USER = 'Rolandfouda499@gmail.com'  
EMAIL_HOST_PASSWORD = 'jrmv ynip kyys cskm'
EMAIL_USE_TLS = True  
SITE_URL = "http://127.0.0.1:8000"


CORS_ALLOWED_ORIGINS
#####################################
# from corsheaders.defaults import default_headers

# CORS_ALLOW_ALL_ORIGINS = False  # Sécurisé, on autorise uniquement Vercel
# CORS_ALLOWED_ORIGINS = [
#     "https://ton-site-vercel.app",  # Remplace par ton URL frontend sur Vercel
# ]
# CORS_ALLOW_CREDENTIALS = True  # Si tu utilises des cookies pour l'authentification

# CSRF_TRUSTED_ORIGINS = [
#     "https://ton-site-vercel.app",  # Autorise les requêtes sécurisées
# ]

CORS_ALLOW_CREDENTIALS = True  # Si tu utilises des cookies pour l'authentification
CORS_ALLOW_METHODS = [
    "GET", "POST", "PUT", "DELETE", "OPTIONS"
]
CORS_ALLOW_HEADERS = [
    "Content-Type", "Authorization", "X-Requested-With"
]
