# Generated by Django 4.2 on 2025-02-12 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_global', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('quantite_recolte', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('pourcentage_papaye_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes mûres')),
                ('pourcentage_papaye_non_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes non mûres')),
                ('pourcentage_papaye_semi_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes semi-mûres')),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueRecolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100)),
                ('quantite_recolte', models.FloatField()),
                ('quantite_non_recolter', models.FloatField()),
                ('pourcentage_papaye_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes mûres')),
                ('pourcentage_papaye_non_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes non mûres')),
                ('pourcentage_papaye_semi_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes semi-mûres')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='Fruit.rapport')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fruit.secteur')),
            ],
        ),
        migrations.AddField(
            model_name='rapport',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fruit.secteur'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Papaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stade_maturation', models.CharField(choices=[('vert', 'Vert'), ('semi-mur', 'Semi-mûr'), ('mur', 'Mûr')], default='vert', max_length=20)),
                ('date_derniere_analyse', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='papayes/', verbose_name='Image des papayes')),
                ('pourcentage_papaye_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes mûres')),
                ('pourcentage_papaye_non_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes non mûres')),
                ('pourcentage_papaye_semi_mur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes semi-mûres')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papayes', to='Fruit.secteur')),
            ],
            options={
                'verbose_name': 'Fruit',
                'verbose_name_plural': 'Fruits',
                'ordering': ['date_derniere_analyse'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('Email', 'Email')], max_length=50)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=False)),
                ('statut_lecture', models.BooleanField(default=False)),
                ('papaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fruit.papaye')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
