# Generated by Django 4.2 on 2025-01-30 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Papaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stade_maturation', models.CharField(choices=[('vert', 'Vert'), ('semi-mûr', 'Semi-mûr'), ('mûr', 'Mûr')], default='vert', max_length=20)),
                ('date_derniere_analyse', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='papayes/', verbose_name='Image des papayes')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papayes', to='Fruit.secteur')),
            ],
            options={
                'verbose_name': 'Fruit',
                'verbose_name_plural': 'Fruits',
                'ordering': ['date_derniere_analyse'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('App', 'Notification Mobile')], max_length=50)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=False)),
                ('papaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fruit.papaye')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
