# Generated by Django 4.2 on 2025-01-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerte',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='secteur',
            old_name='user',
            new_name='utilisateur',
        ),
    ]
