# Generated by Django 4.2 on 2025-01-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0002_rename_user_alerte_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papaye',
            name='image',
            field=models.FileField(upload_to='papayes/', verbose_name='Image des papayes'),
        ),
    ]
