# Generated by Django 4.2 on 2025-02-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0003_alter_papaye_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='statut_lecture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_notification',
            field=models.CharField(choices=[('Email', 'Email')], max_length=50),
        ),
    ]
