# Generated by Django 4.2 on 2025-02-01 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fruit', '0004_alerte_statut_lecture_alter_alerte_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secteur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
