# Generated by Django 4.2 on 2025-02-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0005_alter_secteur_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papaye',
            name='stade_maturation',
            field=models.CharField(choices=[('vert', 'Vert'), ('semi-mur', 'Semi-mûr'), ('mur', 'Mûr')], default='vert', max_length=20),
        ),
    ]
