# Generated by Django 4.2 on 2025-02-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0007_rapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueRecolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100)),
                ('quantite_recolte', models.FloatField()),
                ('quantite_perdu', models.FloatField()),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fruit.secteur')),
            ],
        ),
    ]
