# Generated by Django 4.2 on 2025-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0008_statistiquerecolte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='quantite_recolte',
            field=models.FloatField(),
        ),
    ]
