# Generated by Django 4.2 on 2025-02-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0009_alter_rapport_quantite_recolte'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiquerecolte',
            name='rapport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='Fruit.rapport'),
            preserve_default=False,
        ),
    ]
