# Generated by Django 4.2 on 2025-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0010_statistiquerecolte_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='papaye',
            name='pourcentage_papaye_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes mûres'),
        ),
        migrations.AddField(
            model_name='papaye',
            name='pourcentage_papaye_non_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes non mûres'),
        ),
        migrations.AddField(
            model_name='papaye',
            name='pourcentage_papaye_semi_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes semi-mûres'),
        ),
    ]
