# Generated by Django 4.2 on 2025-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0011_papaye_pourcentage_papaye_mur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistiquerecolte',
            old_name='quantite_perdu',
            new_name='quantite_non_recolter',
        ),
        migrations.AddField(
            model_name='rapport',
            name='pourcentage_papaye_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes mûres'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='pourcentage_papaye_non_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes non mûres'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='pourcentage_papaye_semi_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes semi-mûres'),
        ),
        migrations.AddField(
            model_name='statistiquerecolte',
            name='pourcentage_papaye_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes mûres'),
        ),
        migrations.AddField(
            model_name='statistiquerecolte',
            name='pourcentage_papaye_non_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes non mûres'),
        ),
        migrations.AddField(
            model_name='statistiquerecolte',
            name='pourcentage_papaye_semi_mur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de papayes semi-mûres'),
        ),
    ]
