# Generated by Django 4.2 on 2025-02-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0012_rename_quantite_perdu_statistiquerecolte_quantite_non_recolter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_non_mur', models.FloatField(default=0)),
                ('total_semi_mur', models.FloatField(default=0)),
                ('total_mur', models.FloatField(default=0)),
                ('nombre_analyses', models.IntegerField(default=0)),
                ('secteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maturation_stats', to='Fruit.secteur')),
            ],
        ),
    ]
