# Generated by Django 4.2 on 2025-02-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0013_maturationstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturationstats',
            name='mois',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
