# Generated by Django 4.2 on 2025-03-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0014_maturationstats_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturationstats',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maturation_stats', to='Fruit.secteur'),
        ),
        migrations.AddConstraint(
            model_name='maturationstats',
            constraint=models.UniqueConstraint(fields=('secteur', 'mois'), name='unique_secteur_mois'),
        ),
    ]
